image: python:3.6.8

pipelines:
  default:
    - step:
        name: test
        caches:
          - pip
        script:
            - pip install nox==2020.8.22
            - pip install poetry==1.0.10
            - pip install nox-poetry==0.5.0
            - nox
    - step:
        name: coverage
        caches:
          - pip
        script:
          - pip install nox==2020.8.22
          - pip install poetry==1.0.10
          - pip install nox-poetry==0.5.0
          - nox --sessions test coverage -- -t $CODECOV_TOKEN
  branches:
    master:
      - step:
          name: test
          caches:
            - pip
          script:
              - pip install nox==2020.8.22
              - pip install poetry==1.0.10
              - pip install nox-poetry==0.5.0
              - nox
      - step:
          name: coverage
          caches:
            - pip
          script:
            - pip install nox==2020.8.22
            - pip install poetry==1.0.10
            - pip install nox-poetry==0.5.0
            - nox --sessions test coverage -- -t $CODECOV_TOKEN
      - step:
          name: build
          caches:
              - pip
          script:
            - pip install nox==2020.8.22
            - pip install poetry==1.0.10
            - pip install nox-poetry==0.5.0
            - nox --sessions build
            - git add setup.py
            - git commit -m "[CI] Updating setup.py to latest version."
            - VERSION = $(poetry version | awk  '{print $2}')
            - TAG = "v$VERSION"
            - git tag $TAG
            - git push