image: python:3.6.8

pipelines:
  default:
    - step:
        name: test
        caches:
          - pip
        script:
            - pip install nox==2020.8.22
            - pip install poetry==1.0.10
            - pip install nox-poetry==0.5.0
            - nox
  branches:
    master:
    - step:
        name: build
        caches:
            - pip
        script:
            - pip install poetry==1.0.10
            - poetry build
            - pipe: atlassian/bitbucket-upload-file:0.3.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "dist/fclearn*.tar.gz"